package com.podkopaev.alexander.itsm.naumen.model

import com.podkopaev.alexander.itsm.globalitsm.model.ItsmCall

class NaumenCall : ItsmCall() {
    data class NaumenServiceCall(
        val KBtoAddArticle: Any,
        val KEs: List<Any>,
        val UUID: String,
        val addArtikle: Any,
        val agreement: Any,
        val author: Any,
        val baseCategory: Any,
        val bpmRoute: Any,
        val categories: List<Any>,
        val client: Employee,
        val clientEmail: Any,
        val clientEmployee: Employee,
        val clientHead: Employee,
        val clientLinkName: String,
        val clientName: String,
        val clientOU: NaumenOU.NaumenOuInfo,
        val clientPhone: Any,
        val clientTeam: Any,
        val closedBy: Any,
        val closedByEmployee: Any,
        val closedByTeam: Any,
        val codeOfClosing: Any,
        val coloOverdue: Any,
        val commentAdded: Boolean,
        val creationDate: String,
        val dateDecision: String,
        val deadLineTime: String,
        val description: String,
        val descriptionInRTF: Any,
        val descriptionRTF: String,
        val folders: List<Any>,
        val icon: Any,
        val impact: Any,
        val lastModifiedDate: String,
        val mark: Any,
        val massProblem: Boolean,
        val massProblemSlaves: List<Any>,
        val masterMassProblem: Any,
        val metaClass: String,
        val negotiations: List<Any>,
        val number: Int,
        val overdue: Any,
        val postoponeTill: Any,
        val priority: Any,
        val problems: List<Any>,
        val processingTimeTimer: Any,
        val reactionTime: Any,
        val registrationDate: String,
        val removalDate: Any,
        val removed: Boolean,
        val requestDate: String,
        val resolutionCode: Any,
        val resolutionTime: Int,
        val responsible: Any,
        val responsibleEmployee: Any,
        val responsibleStartTime: Any,
        val responsibleTeam: Any,
        val resultDescr: String,
        val resumed: Boolean,
        val resumptionSum: Int,
        val rfcReason: List<Any>,
        val rfcResults: List<Any>,
        val service: Any,
        val serviceTime: Any,
        val shortDescr: String,
        val slaved: Boolean,
        val solvedBy: Any,
        val solvedByEmployee: Any,
        val solvedByTeam: Any,
        val spentTime: Any,
        val startTime: String,
//        val state: String,
        val stateStartTime: String,
        val subscribers: List<Any>,
        val system_icon: Any,
        val tasks: List<Any>,
        val teamMessageId: Any,
        val timeAllowanceTimer: Any,
        val timeClosing24: Any,
        val timeForAccept: Any,
        val timeZone: Any,
//        val title: String,
        val titleKB: Any,
        val totalTimeTimer: Any,
        val urgency: Any,
        val userDoc: List<Any>,
        val wayAddressing: Any,
        val wfProfile: Any,
        val workRecords: List<Any>
    ) : ItsmCall.ItsmServiceCall()

    data class Employee(
        val UUID: String,
        val metaClass: String,
        val title: String
    )
}